### PR TITLE
Model

### PR DESCRIPTION
**Pull request by lordtt13**
Data converted to RNN compatible datasets

### CODE REVIEW

**Comment by achhapolia10** [comment]
@lordtt13 when the model is completed and branch is ready to be merged message me.

**Comment by lordtt13** [comment]
I will, most probably in a day or two.

Will continue adding to the model as parsed data keeps coming in.

**Comment by lordtt13** [comment]
First training model on first batch of parsed data added
Please note that cos phi data causes mode collapse

Please check and merge

**Review by achhapolia10 — CHANGES_REQUESTED** [review]
Please remove the model binaries.

**Comment by lordtt13** [comment]
Let them remain as the stable release, as I'll be retraining on many new instances and will need a stable reference

**Review by achhapolia10 — APPROVED** [review]

**Pull request merged**
